fix: update netbeansWrapper

diff --git a/bin/netbeansWrapper b/bin/netbeansWrapper
--- a/bin/netbeansWrapper
+++ b/bin/netbeansWrapper
@@ -2,16 +2,34 @@
 
 DISPLAY_NUM=":1"
 RESOLUTION="1920x1080"
+CONF_FILE="$HOME/.config/openbox/xephyr-rc.xml"
+CLIPSYNC_CMD="/home/wtf/.local/bin/clipsync"
 
 if ! pgrep -f "Xephyr ${DISPLAY_NUM}" > /dev/null; then
-    Xephyr ${DISPLAY_NUM} -screen ${RESOLUTION} -dpi 110 -resizeable -host-cursor -ac +extension RANDR &
+    Xephyr ${DISPLAY_NUM} -screen ${RESOLUTION} -dpi 110 -resizeable -host-cursor -ac +extension RANDR -extension MIT-SHM &
     sleep 1
 fi
 
-DISPLAY=${DISPLAY_NUM} XCURSOR_THEME=Sweet-cursors XCURSOR_SIZE=24 \
-    matchbox-window-manager -use_titlebar no -use_desktop_mode plain &
+$CLIPSYNC_CMD
+
+DISPLAY=${DISPLAY_NUM} openbox --config-file "$CONF_FILE" &
 sleep 0.5
 
-DISPLAY=${DISPLAY_NUM} XCURSOR_THEME=Sweet-cursors XCURSOR_SIZE=24 netbeans "$@"
+if ! flatpak list --app | grep -q "org.apache.netbeans"; then
+    echo "Installing Netbeans. Please Wait..."
+    flatpak install -y flathub org.apache.netbeans
+    if [ $? -ne 0 ]; then
+        echo "Failed to install Netbeans. exit..."
+        pkill -f "Xephyr ${DISPLAY_NUM}" 2>/dev/null
+        exit 1
+    fi
+fi
 
+DISPLAY=${DISPLAY_NUM} XCURSOR_THEME=Sweet-cursors XCURSOR_SIZE=24 \
+    flatpak run org.apache.netbeans \
+    -J-Dawt.useSystemAAFontSettings=lcd \
+    -J-Dswing.aatext=true \
+    "$@"
+
+$CLIPSYNC_CMD --stop
 pkill -f "Xephyr ${DISPLAY_NUM}" 2>/dev/null
